kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: phaefelfinger/tv7playlist
      tags:
        - latest
        - '3.1'
        - '3.1.0'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - master